# Online News Popularity

Database:

In [12]:
from sklearn.datasets import make_regression
import numpy as np
import pandas as pd
%matplotlib notebook
from matplotlib import pyplot as plt
import scipy.stats
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split

# Visualitzarem només 3 decimals per mostra
pd.set_option('display.float_format', lambda x: '%.3f' % x)

# Funcio per a llegir dades en format csv
def load_dataset(path):
    dataset = pd.read_csv(path, header=0, delimiter=',')
    return dataset

# Carreguem dataset d'exemple
dataset = load_dataset('OnlineNewsPopularity.csv')
data = dataset.values

x = data[:, :60]
y = data[:, 60]

x_t, x_v, y_t, y_v = train_test_split(x, y, train_size=0.5)

In [4]:
print("Per comptar el nombre de valors no existents:")
print(dataset.isnull().sum())

Per comptar el nombre de valors no existents:
url                              0
 timedelta                       0
 n_tokens_title                  0
 n_tokens_content                0
 n_unique_tokens                 0
                                ..
 title_subjectivity              0
 title_sentiment_polarity        0
 abs_title_subjectivity          0
 abs_title_sentiment_polarity    0
 shares                          0
Length: 61, dtype: int64

In [5]:
print("Per visualitzar les primeres 5 mostres de la BBDD:")
dataset.head()

Per visualitzar les primeres 5 mostres de la BBDD:

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.000,12.000,219.000,0.664,1.000,0.815,4.000,2.000,1.000,...,0.100,0.700,-0.350,-0.600,-0.200,0.500,-0.188,0.000,0.188,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.000,9.000,255.000,0.605,1.000,0.792,3.000,1.000,1.000,...,0.033,0.700,-0.119,-0.125,-0.100,0.000,0.000,0.500,0.000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.000,9.000,211.000,0.575,1.000,0.664,3.000,1.000,1.000,...,0.100,1.000,-0.467,-0.800,-0.133,0.000,0.000,0.500,0.000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.000,9.000,531.000,0.504,1.000,0.666,9.000,0.000,1.000,...,0.136,0.800,-0.370,-0.600,-0.167,0.000,0.000,0.500,0.000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.000,13.000,1072.000,0.416,1.000,0.541,19.000,19.000,20.000,...,0.033,1.000,-0.220,-0.500,-0.050,0.455,0.136,0.045,0.136,505

In [6]:
print("Per veure estadístiques dels atributs numèrics de la BBDD:")
dataset.describe()

Per veure estadístiques dels atributs numèrics de la BBDD:

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
count,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,...,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000,39644.000
mean,354.530,10.399,546.515,0.548,0.996,0.689,10.884,3.294,4.544,1.250,...,0.095,0.757,-0.260,-0.522,-0.108,0.282,0.071,0.342,0.156,3395.380
std,214.164,2.114,471.108,3.521,5.231,3.265,11.332,3.855,8.309,4.108,...,0.071,0.248,0.128,0.290,0.095,0.324,0.265,0.189,0.226,11626.951
min,8.000,2.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,-1.000,-1.000,-1.000,0.000,-1.000,0.000,0.000,1.000
25%,164.000,9.000,246.000,0.471,1.000,0.626,4.000,1.000,1.000,0.000,...,0.050,0.600,-0.328,-0.700,-0.125,0.000,0.000,0.167,0.000,946.000
50%,339.000,10.000,409.000,0.539,1.000,0.690,8.000,3.000,1.000,0.000,...,0.100,0.800,-0.253,-0.500,-0.100,0.150,0.000,0.500,0.000,1400.000
75%,542.000,12.000,716.000,0.609,1.000,0.755,14.000,4.000,4.000,1.000,...,0.100,1.000,-0.187,-0.300,-0.050,0.500,0.150,0.500,0.250,2800.000
max,731.000,23.000,8474.000,701.000,1042.000,650.000,304.000,116.000,128.000,91.000,...,1.000,1.000,0.000,0.000,0.000,1.000,1.000,0.500,1.000,843300.000

In [20]:
print("Longitud de X_Train: ") 
print(len(x_t))
print("Longitud de X_Validation: ") 
print(len(x_v))
print("Longitud de Y_Train: ") 
print(len(y_t))
print("Longitud de Y_Validation: ") 
print(len(y_t))

Longitud de X_Train:
19822